organizations:

  organization:
    displayName: ${domain}

folders:

  folder_devops:
    displayName : ${folder_devops}
    parent: organizations/organization

  folder_management:
    displayName: ${folder_management}
    parent: organizations/organization

projects:

  project_control:
    displayName: ${project_control}
    parent: folders/folder_devops
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - cloudkms.googleapis.com             # - For CMEK keys
    - storage.googleapis.com              # - For storage buckets (terraform state)
    - cloudresourcemanager.googleapis.com # - Required for running terraform
    - serviceusage.googleapis.com         # - Required for running terraform 
    - iam.googleapis.com                  # - Required for running terraform
    - cloudbuild.googleapis.com           # - Required for running terraform
    - cloudasset.googleapis.com           # - Required for running terraform
    - orgpolicy.googleapis.com            # - Required for running terraform
    - pubsub.googleapis.com               # - Required for running terraform
    - bigquery.googleapis.com             # - Required for running terraform
    - bigquerymigration.googleapis.com    # - Enabled by google as dependency
    - bigquerystorage.googleapis.com      # - Enabled by google as dependency
    serviceAccounts:
    - name: ${sa_devops}
      displayName: Pipeline ${folder_devops} 
      description: Cloudbuild Service Account for ${folder_devops} folder
    - name: ${sa_management}
      displayName: Pipeline ${folder_management}
      description: Cloudbuild Service Account for ${folder_management} folder  
    storage:
    - name: ${bucket_tfstate}

  project_pipelines:
    displayName: ${project_pipelines}
    parent: folders/folder_devops
    services:       
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - serviceusage.googleapis.com         # - For enabling services 
    - cloudkms.googleapis.com             # - For CMEK keys
    - storage.googleapis.com              # - For storage buckets (cloudbuild outputs)
    - artifactregistry.googleapis.com     # - For docker images
    - sourcerepo.googleapis.com           # - For cloud source repositories
    - cloudbuild.googleapis.com           # - For cloud build triggers
    - logging.googleapis.com              # - Enabled by google - dependency on cloudbuild
    - pubsub.googleapis.com               # - Enabled by google - dependency on source repos
    - storage-api.googleapis.com          # - Enabled by google - dependency on cloudbuild?
    - iam.googleapis.com                  # - Required for pipelines?
    serviceAccounts:
    - name: ${sa_guardrail_orgpolicy}
      displayName: Guardrail Organization Policy
      description: Cloudfunction Service Account for Organization Policy Guardrail

  project_logging:
    displayName: ${project_logging}
    parent: folders/folder_management
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - cloudkms.googleapis.com             # - For CMEK keys
    - bigquery.googleapis.com             # - For logging to bigquery
    - bigquerymigration.googleapis.com    # - Enabled by google as dependency
    - bigquerystorage.googleapis.com      # - Enabled by google as dependency

  project_billing:
    displayName: ${project_billing}
    parent: folders/folder_management
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - bigquery.googleapis.com             # - For billing to bigquery

  project_guardrails: 
    displayName: ${project_guardrails}
    parent: folders/folder_management
    services: 
    - compute.googleapis.com              # - Enabled by google by default
    - oslogin.googleapis.com              # - Enabled by google by default
    - cloudkms.googleapis.com             # - For CMEK keys
    - storage.googleapis.com              # - For cloud functions
    - artifactregistry.googleapis.com     # - For cloud functions
    - pubsub.googleapis.com               # - For cloud functions
    - cloudbuild.googleapis.com           # - For cloud functions
    - cloudfunctions.googleapis.com       # - For guardrails
